name: Testing
on:
  push:
    branches:
      - master
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.3'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install
      - name: PHPStan
        run: vendor/bin/phpstan analyse src --level=max
      - name: Pint
        run: vendor/bin/pint --test
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.3'
          extensions: gd
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --no-scripts
      - name: Run test
        run: ./vendor/bin/phpunit